baseURL = "https://securityunlocked.com/"
title   = "Security Unlocked"
theme   = "PaperMod"

[pagination]
  pagerSize = 10

[params]
  defaultTheme = "light"
  disableThemeToggle = true
  ShowReadingTime = true
  ShowShareButtons = false
  ShowCodeCopyButtons = true
  mainSections = ["articles"]

[menu]
  [[menu.main]]
    name = "Home"
    url = "/"
    weight = 1
  [[menu.main]]
    name = "Articles"
    url = "/articles/"
    weight = 2
  [[menu.main]]
    name = "About"
    url = "/about/#contact"
    weight = 3
  [[menu.main]]
    name = "Contact"
    url = "/contact/"
    weight = 4
